name 'yum-repoforge'
maintainer 'Chef'
maintainer_email 'Sean OMeara <someara@chef.io>'
license 'Apache 2.0'
description 'Installs/Configures yum-repoforge'
version '0.5.1'
source_url 'https://github.com/chef-cookbooks/yum-repoforge'
issues_url 'https://github.com/chef-cookbooks/yum-repoforge/issues'

depends 'yum', '~> 3.0'
depends 'yum-epel'
